### ISSUE TITLE
yaml.dump of spec.to_dict() results in invalid spec

### ISSUE THREAD

**Issue by daenney** [marshmallow-code/apispec#161]
I'm trying to dump the spec to YAML with `yaml.dump(spec.to_dict())` but that results in an invalid representation due to entries like these:

```yaml
  - - /api/v0/groups
    - !!python/object/new:apispec.core.Path
```

Or, for items:
```yaml
items:
                  properties: !!python/object/new:apispec.lazy_dict.LazyDict
```
```yaml
403:
              description: You are not authorized to request this resource
              schema:
                properties: !!python/object/new:apispec.lazy_dict.LazyDict
                  dictitems:
                    code: {format: int32, type: integer}
                    error: {type: string}
                required: [code, error]
                type: object
```

In order to dump this correctly it seems we'd need a custom YAML dumper for apispec. Use `safe_dumper` isn't possible either since it doesn't know how to dump certain of these objects.
