### ISSUE TITLE
Add description to fields of marshmallow generated schema

### ISSUE THREAD

**Issue by UrKr** [marshmallow-code/apispec#208]
Is it possible to add additional fields to OpenAPI schemas generated via marshmallow `Schema`. One example would be descriptions for fields. 

```
class ASchema(Schema):
    a = fields.Int()
```
```
    ASchema:
      properties:
        a:
          type: integer
          description: 'description for a field'
      type: object
      description: 'description for a schema'
```
Currently docstrings on schemas are ignored, correct?

**Comment by sloria** [comment]
There isn't a way to add additional properties to schemas right now. Docstrings don't have an effect on the output.

I'm open to adding support for it. Should description automatically be set to the content of the docstring, or should it be specified in YAML?

**Comment by fMeow** [comment]
For description for fields, just pass a keyword arguments like this:
```python
class ASchema(Schema):
    a = fields.Int(description="description for a field")
```

As for description for schemas, there may be a better way to do this. For example, when a schema is defined in a parameter, there is no need to assign a description for the schema. Instead, it is the parameter object that has a description. 

Some examples:
- definition
```python
class ASchema(Schema):
    a = fields.Int(description="description for a field")

spec.definition('ASchema', schema=ASchema, description="description for a definition, or a schema")
```
And the code above yields following result:  
```yaml
components:
  schemas:
    ASchema:
      properties:
        id: {description: description for a field, format: int32, type: integer}
      description: description for a definition, or a schema
      type: object
```
- parameter
```yaml
    get:
        parameters:
            - in: query
              description: description for a parameter
              schema: ASchema
```

And in my opinion, there is no need to add descriptions for schemas.
