### ISSUE TITLE
Add support for `summary` and `description` fields for paths

### ISSUE THREAD

**Issue by timakro** [marshmallow-code/apispec#227]
Documented [here](https://swagger.io/docs/specification/paths-and-operations/):

> Paths may have an optional short summary and a longer description for documentation purposes. This information is supposed to be relevant to all operations in this path. description can be multi-line and supports Markdown (CommonMark) for rich text representation.

**Comment by brunoais** [comment]
I don't get what you mean. What kind of support from apispec is needed for that?

**Comment by timakro** [comment]
[This check](https://github.com/marshmallow-code/apispec/blob/56b12fbb85224fc93284032986a55c8fa3d1168c/apispec/core.py#L76-L78) prevents you from using them.

**Comment by brunoais** [comment]
That check only checks for HTTP methods and not what you describe above.
What you describe above is nested inside the HTTP method

**Comment by timakro** [comment]
`summary` and `description` are also allowed for paths:

```yaml
    paths:
      /users/{id}:
        summary: Represents a user
        description: >
          This resource represents an individual user in the system.
          Each user is identified by a numeric `id`.
        get:
          ...
        patch:
          ...
        delete:
          ...
```
