### ISSUE TITLE
Support for OpenAPI Links?

### ISSUE THREAD

**Issue by fsabr** [marshmallow-code/apispec#615]
Is there support for [OpenAPI Links](https://swagger.io/docs/specification/links/)? I couldn't find it anywhere.

Manually adding the following to the docstring works
```yaml
links:
    Get User By Id:
        operationId: UserGet
        parameters:
            id: $response.body#/id
```
but I don't think the validation part works, as something like this
```yaml
links:
    Get User By Id:
        operationId: UserGet
        parameters:
            id: RandomString
```
also validates (using `apispec.utils.validate_spec`).
